config/routes.rb
Rails.application.routes.draw do
  get '/pictures',to:'pictures#index'
  get '/pictures/new',to:'pictures#new'
  post '/pictures',to:'pictures#create'
  get '/pictures/:id',to:'pictures#show',as:'picture'
  get '/pictures/:id/edit',to:'pictures#edit',as:'edit_picture'
  patch '/pictures/:id/edit',to:'pictures#update'
  delete '/pictures/:id',to:'pictures#destroy',as:'destroy_picture'
  post '/pictures/confirm',to:'pictures#confirm',as:'confirm_picture'

  get '/users/new',to:'users#new'
  post '/users',to:'users#create'
  get '/users/:id',to:'users#show',as:'user'
  get '/users/:id/edit',to:'users#edit',as:'edit_user'
  patch '/users/:id',to:'users#update'
  get 'users/:id/favorites',to:'users#favorites',as:'favorites_picture'

  get '/sessions/new',to:'sessions#new'
  post '/sessions/new',to:'sessions#create'
  delete '/session/:id',to:'sessions#destroy',as:'destroy_session'

  resources :favorites,only:[:create,:destroy]

  mount LetterOpenerWeb::Engine, at: "/inbox"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image,ImageUploader
  validates :word,presence:true,length:{maximum:150}
  validates :image,presence:true
  belongs_to :user
  has_many :favorites,dependent: :destroy
  has_many :favorite_users,through: :favorites,source: :user
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image,ImageUploader
  validates :name,presence:true,length:{maximum:30}
  validates :email,presence:true,length:{maximum:255},
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation{ email.downcase! }
  has_secure_password
  validates :password,presence:true,length:{minimum:6}
  has_many :pictures
  has_many :favorites,dependent: :destroy
  has_many :favorite_picture,through: :favorites,source: :picture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def authenticate_user
    if current_user == nil
      redirect_to sessions_new_path,notice:"ログインが必要です"
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    @favorites = current_user.favorite_picture
  end

  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_url,notice:"#{favorite.picture.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_url,notice:"#{favorite.picture.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture,only:[:show,:edit,:update,:destroy,:ensure_correct_user_p]
  before_action :ensure_correct_user_p,only:[:edit,:update,:destroy]
  before_action :authenticate_user,only:[:new,:create,:show,:edit,:update,:destroy]

  def index
    @pictures = Picture.all
  end

  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    if @picture.save
      PictureMailer.picture_mail(@picture).deliver
      redirect_to pictures_path,notice: "投稿しました!"
    else
      render 'new'
    end
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def edit
  end

  def update
    if @picture.update(picture_params)
      redirect_to picture_path,notice:"編集が完了しました!"
    else
      render "edit"
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_path,notice:"投稿を削除しました！"
  end

  def confirm
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    render :new if @picture.invalid?
  end

  def ensure_correct_user_p
    if @picture.user_id != current_user.id
      redirect_to pictures_path,notice:"権限がありません"
    end
  end

  private

  def picture_params
    params.require(:picture).permit(:word,:image,:image_cache)
  end

  def set_picture
    @picture = Picture.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email:params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = "ログインに失敗しました"
      render "new"
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "ログアウトしました"
    redirect_to sessions_new_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user,only:[:show,:edit,:update,:favorites,:ensure_correct_user_u]
  before_action :authenticate_user,only:[:show,:edit,:update]
  before_action :ensure_correct_user_u,only:[:edit,:update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id), notice: "アカウントを作成しました!"
    else
      render'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id),notice:"ユーザープロフィールを編集しました！"
    else
      render "edit"
    end
  end

  def favorites
    @favorites = @user.favorite_picture
  end

  def ensure_correct_user_u
    if @user.id != current_user.id
      redirect_to pictures_path,notice:"権限がありません"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation,:image,:image_cache)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == "new" || action_name == "confirm"
      confirm_picture_path
    elsif action_name == "edit"
      edit_picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id:session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
            <span class="sr-only">InstagramClone</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <span class="navbar-brand"><%= link_to "InstagramClone",pictures_path,:style=>"color:black;" %></span>
        </div>
        <div id="gnavi" class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <li><%= link_to current_user.name,user_path(current_user.id) %></li>
              <li><%= link_to "新規投稿",pictures_new_path %></li>
              <li><%= link_to "ログアウト",destroy_session_path(current_user.id),method: :delete %></li>
            <% else %>
              <li><%= link_to "アカウント新規登録",users_new_path %></li>
              <li><%= link_to "ログイン",sessions_new_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
      <div class="container-fluid">
        <div class="row">
          <div class="col-xs-offset-1 col-md-offset-5">
            <% if flash[:notice] %>
              <p><%= flash[:notice] %></p>
            <% end %>
            <%= yield %>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model:@picture,local: true,url:choose_new_or_edit) do |form| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :本文 %>
    <%= form.text_area :word,size: "30x8" %>
  </div>

  <div class="field">
    <%= form.label :画像 %>
    <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="actions">
    <%= form.submit :投稿する %>
  </div>
<% end %>

app/views/pictures/confirm.html.erb
<h3>この内容でよろしいですか？</h3>
<%= form_with(model:@picture,url:pictures_path,local:true) do |form| %>
  <%= form.hidden_field :word %>
  <%= form.hidden_field :image %>

  <p class="word"><%= @picture.word %></p>
  <p><%= image_tag(@picture.image.url) if @picture.image && @picture.image.url%></p>
  <%= form.hidden_field :image_cache %>
  <p class="actions"><%= form.submit "投稿する" %></p>
<% end %>

<%= form_with(model: @picture,url:pictures_new_path,local:true,method:"get") do |form| %>
  <%= form.hidden_field :word %>
  <%= form.hidden_field :image_cache %>
  <p class="actions"><%= form.submit "戻る", name:"back" %></p>
<% end %>

app/views/pictures/edit.html.erb
<h1>投稿編集</h1>

<%= render 'form',picture: @picture %>

<%= link_to '投稿一覧に戻る',pictures_path %>

app/views/pictures/index.html.erb
<h1>投稿一覧</h1>

<% @pictures.each do |picture| %>
  <div><%= link_to picture.user.name,user_path(picture.user.id) %></div>
  <div>
  <% if logged_in? %>
    <%= link_to image_tag(picture.image.url),picture_path(picture.id) %>
  <% else %>
    <%= image_tag(picture.image.url) %>
  <% end %>
  </div>
  <br>
<% end %>

app/views/pictures/new.html.erb
<h1>新規投稿</h1>

<%= render 'form', picture: @picture %>

app/views/pictures/show.html.erb
<h1>投稿詳細</h1>

<div><%= link_to @picture.user.name,user_path(@picture.user.id) %></div>
<div class="word"><%= @picture.word %></div>
<div><%= image_tag(@picture.image.url) %></div>

<% if @picture.user_id == current_user.id %>
    <span class="mgr-10"><%= link_to "編集",edit_picture_path(@picture.id) %></span>
    <%= link_to "削除",destroy_picture_path(@picture.id),method: :delete,data:{confirm:"本当に削除しますか？"} %>
<% end %>

<% unless @picture.user_id == current_user.id %>
    <% if @favorite.present? %>
      <%= link_to 'お気に入り解除する',favorite_path(id:@favorite.id),method: :delete %>
    <% else %>
      <%= link_to 'お気に入りする',favorites_path(picture_id: @picture.id),method: :post %>
    <% end %>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: @user,local: true) do |f|%>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </p>
  <p class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>
  <p class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="field">
    <%= f.file_field :image %>
    <%= image_tag(@user.image.url) if @user.image && @user.image.url %>
    <%= f.hidden_field :image_cache %>
  </p>
  <p class="actions">
    <%= f.submit "入力完了" %>
  </p>
<% end %>

app/views/users/edit.html.erb
<h1>ユーザープロフィール編集</h1>

<%= render 'form', user: @user %>

app/views/users/favorites.html.erb
<h1>お気に入り一覧</h1>
<% @favorites.each do |favorite| %>
  <p><%= favorite.user.name %></p>
  <p><%= link_to favorite.word,picture_path(favorite.id) %></p>
  <p><%= link_to image_tag(favorite.image.url),picture_path(favorite.id) %></p>
<% end %>

app/views/users/new.html.erb
<h1>サインアップ</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス:<%= @user.email %></p>

<p><%= image_tag(@user.image.url) if @user.image && @user.image.url %></p>

<% if @user.id == current_user.id %>
  <span class="mgr-10"><%= link_to "編集",edit_user_path(@user.id) %></span>
<% end %>
<%= link_to "お気に入り投稿一覧",favorites_picture_path %>